version: '3.7'

services:
    db:
       image: "mysql:8.0.30"
       restart: always
       command: --default-authentication-plugin=caching_sha2_password 
       environment:
            MYSQL_DATABASE: web
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_USER: appuser
            MYSQL_PASSWORD: '123456'  
       
       ports: 
               - '3307:3306'
       volumes:
               - db-blog:/var/lib/mysql

       container_name: db        
   
    web: 
       build: ./
       command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
       volumes:
               - app-blog:/blog
       ports: 
               - '8080:8080'
       restart: always
       network_mode: "host" 
       depends_on:
               - db
       environment:
            DB_USER: root
            DB_NAME: web
            DB_PASSWORD: 123456
            DB_HOST: db
volumes:
        db-blog: 
        app-blog:   
